>>> 100/5
20.0
>>> type(100/5)
<class 'float'>
>>> type(7/2)
<class 'float'>
>>> type(7//2)
<class 'int'>
>>> type(7%2)
<class 'int'>
>>> type("a")
<class 'str'>
>>> type("tiza"+".")
<class 'str'>
>>> type("hola"[1+1])
<class 'str'>
>>> type(len("hola"))
<class 'int'>
>>> type(int("145"))
<class 'int'>
>>> type(float("145"))
<class 'float'>
>>> type(float(145))
<class 'float'>
>>> type(str(32))
<class 'str'>
>>> type(1+2!=3)
<class 'bool'>
>>> type(177%2==0)
<class 'bool'>
>>> type(len("nube")<=20)
<class 'bool'>
>>> 
